#!/usr/bin/env bash
set -euo pipefail

BASE="/mnt/myvolume/panel_seq/new_bed_analysis"
PAIRS_CSV="${PAIRS_CSV:-${BASE}/pairs_df_filtered.csv}"
VCF_ROOT="${VCF_ROOT:-${BASE}/vcfs}"
OUTDIR="${OUTDIR:-${BASE}/baf_from_pair_vcfs_clean}"
MIN_DP="${MIN_DP:-10}"
TMPDIR_WORK="$(mktemp -d -p "${TMPDIR:-/tmp}" baf_from_pair_vcfs.XXXXXX)"
TMP_ROWS="${TMPDIR_WORK}/rows"
SKIPPED_LOG="${OUTDIR}/skipped_pairs.tsv"

mkdir -p "${OUTDIR}" "${TMP_ROWS}"
find "${OUTDIR}" -maxdepth 1 -type f \( -name "*.tsv" -o -name "README.md" \) -delete
: > "${SKIPPED_LOG}"

cleanup() {
  rm -rf "${TMPDIR_WORK}"
}
trap cleanup EXIT

echo "Pairs CSV: ${PAIRS_CSV}"
echo "VCF root:  ${VCF_ROOT}"
echo "Out dir:   ${OUTDIR}"
echo "Min DP:    ${MIN_DP}"
echo "Temp dir:  ${TMPDIR_WORK}"

processed_pairs=0
missing_pairs=0
invalid_pairs=0

while IFS=, read -r tumor normal; do
  [[ -n "${tumor}" && -n "${normal}" ]] || continue
  pair="${tumor}__${normal}"
  vcf="${VCF_ROOT}/${pair}/unfiltered.${pair}.vcf.gz"

  if [[ ! -f "${vcf}" ]]; then
    echo "WARN: missing VCF for ${pair}: ${vcf}" >&2
    printf "%s\tmissing\t%s\n" "${pair}" "${vcf}" >> "${SKIPPED_LOG}"
    missing_pairs=$((missing_pairs + 1))
    continue
  fi

  if ! gzip -t "${vcf}" >/dev/null 2>&1; then
    echo "WARN: unreadable VCF for ${pair}: ${vcf}" >&2
    printf "%s\tinvalid_gzip\t%s\n" "${pair}" "${vcf}" >> "${SKIPPED_LOG}"
    invalid_pairs=$((invalid_pairs + 1))
    continue
  fi

  processed_pairs=$((processed_pairs + 1))

  gzip -dc "${vcf}" | awk -F'\t' -v OFS='\t' -v min_dp="${MIN_DP}" -v tmp_rows="${TMP_ROWS}" '
    function is_snp(ref, alt) {
      return (length(ref) == 1 && length(alt) == 1 && alt !~ /,/)
    }
    function is_int(x) {
      return (x ~ /^[0-9]+$/)
    }
    /^##/ { next }
    /^#CHROM/ {
      for (i = 10; i <= NF; i++) {
        samples[i] = $i
        out[i] = tmp_rows "/" $i ".raw.tsv"
      }
      next
    }
    {
      if (!is_snp($4, $5)) next

      split($9, fmt, ":")
      gt_idx = ad_idx = dp_idx = 0
      for (i = 1; i <= length(fmt); i++) {
        if (fmt[i] == "GT") gt_idx = i
        else if (fmt[i] == "AD") ad_idx = i
        else if (fmt[i] == "DP") dp_idx = i
      }
      if (!gt_idx || !ad_idx || !dp_idx) next

      chrom = $1
      pos = $2
      id = chrom "_" pos

      for (i = 10; i <= NF; i++) {
        split($i, vals, ":")
        gt = vals[gt_idx]
        ad = vals[ad_idx]
        dp = vals[dp_idx]

        if (gt == "" || gt == "." || gt == "./." || gt == ".|.") continue
        if (!is_int(dp) || dp < min_dp) continue
        if (ad == "" || ad == ".") continue

        n_ad = split(ad, depths, ",")
        if (n_ad != 2) continue
        if (!is_int(depths[1]) || !is_int(depths[2])) continue

        ref_count = depths[1] + 0
        alt_count = depths[2] + 0
        if (dp <= 0) continue

        baf = alt_count / dp
        print chrom, pos, pos, id, sprintf("%.4f", baf), dp >> out[i]
      }
    }
  '
done < "${PAIRS_CSV}"

generated=0
for raw_file in "${TMP_ROWS}"/*.raw.tsv; do
  [[ -e "${raw_file}" ]] || continue
  sample="$(basename "${raw_file}" .raw.tsv)"
  out_file="${OUTDIR}/${sample}.tsv"

  awk -F'\t' -v OFS='\t' '
    {
      key = $1 FS $2
      dp = $6 + 0
      if (!(key in best_dp) || dp > best_dp[key]) {
        best_dp[key] = dp
        best_line[key] = $0
      }
    }
    END {
      for (key in best_line) {
        print best_line[key]
      }
    }
  ' "${raw_file}" | sort -k1,1V -k2,2n > "${out_file}"

  generated=$((generated + 1))
done

cat > "${OUTDIR}/README.md" <<EOF
# BAF Folder From Pair VCFs

Generated by \`$(basename "$0")\` on $(date -u +"%Y-%m-%d %H:%M:%S UTC").

- Source VCFs: \`${VCF_ROOT}\`
- Pair list: \`${PAIRS_CSV}\`
- Input VCF used per pair: \`unfiltered.<tumor>__<normal>.vcf.gz\`
- SNP filter: biallelic SNVs only
- Per-sample requirements: non-missing \`GT\`, integer \`AD\`, integer \`DP\`, \`DP >= ${MIN_DP}\`
- Output columns: \`chr start end chr_pos baf depth\`
- Duplicate sample occurrences across pairs are merged by genomic position and the highest-depth row is retained.
- Skipped pairs log: \`$(basename "${SKIPPED_LOG}")\`
EOF

echo
echo "Processed pairs: ${processed_pairs}"
echo "Missing pairs:   ${missing_pairs}"
echo "Invalid pairs:   ${invalid_pairs}"
echo "Generated TSVs:  ${generated}"
echo "Output folder:   ${OUTDIR}"
